# Generated by Django 2.1 on 2019-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('is_register', models.BooleanField(default=False)),
                ('host_name', models.CharField(max_length=254)),
                ('ip', models.CharField(max_length=254)),
                ('last_login', models.CharField(max_length=212)),
            ],
        ),
    ]
